tilt-dev/company

support/README.md
Hello @victorwuky, @dbentley,
Please review the following commits I made in branch nicks/exterminator:
49a0a0bf151a59d47503c0b55ac78000bc44a8a2 (2020-03-04 13:42:59 -0500)
support: copy the exterminator rotation
This is just a straight copy-and-paste-and-refpr,at from the working agreement
doc, and shouldn't include any fixes or updates. I plan to send updates (like
fixing broken links) in a subsequent PR
=> support: copy the exterminator rotation

README.md, donations/README.md
Hello @nicks, @dbentley, @victorwuky,
Please review the following commits I made in branch maiamcc/donations:
5436ed11c1f9d1cfcac9f201d28fc1f3fdebf880 (2020-03-04 11:50:07 -0500)
add donations page
=> add donations page

support/README.md
Hello @maiamcc, @victorwuky,
Please review the following commits I made in branch nicks/exterminator2:
1af063efa31579744c119b3baa09515f2a543c67 (2020-03-04 14:56:09 -0500)
support: update the exterminator working agreement to better document the current process
In a subsequent PR, I will propose changes to how we track exterminator load
and run the process. But for now, I just want the doc to better reflect the
current process.
=> support: update the exterminator working agreement to better document the current process

support/README.md
Hello @victorwuky, @maiamcc,
Please review the following commits I made in branch nicks/ch4776/exterminator:
56747119f989268ad2f3588ae43c47ba4de83504 (2020-03-05 16:25:44 -0500)
support: add a proposal for tracking support load
=> support: add a proposal for tracking support load

support/README.md
Hello @nicks, @vw,
Please review the following commits I made in branch maiamcc/exterminator-script:
e835f932f7d29be3c2674450445c89b390a55af5 (2020-03-12 11:58:38 -0400)
link exterminator script
=> link exterminator script

product-principles/README.md
Hello @victorwuky, @dbentley,
Please review the following commits I made in branch nicks/infra-as-data:
6804fd03c9f125dc4d459578e1e85fce14ecb885 (2020-03-17 15:02:42 -0400)
product-principles: infrastructure as data
=> product-principles: infrastructure as data

user-support/README.md
Hello @victorwuky, @landism,
Please review the following commits I made in branch nicks/exterminator:
5dd707d214ff9c5d32ab780154a84b525a4f8916 (2020-03-30 12:56:56 -0400)
exterminator: separate out CRM work from extermination
=> exterminator: separate out CRM work from extermination

donations/README.md
Hello @landism, @victorwuky,
Please review the following commits I made in branch nicks/donation:
9ab5e53ee38aa30cba0bbf73df8100dd9e02cd4b (2020-04-06 18:22:21 -0400)
flesh out the donation rotation
=> flesh out the donation rotation

communications/README.md
Hello @victorwuky, @dbentley,
Please review the following commits I made in branch nicks/holacracy:
5b184cb0f2ab4b8ae8ac35b534a7bc2bad222c6f (2020-05-29 11:20:26 -0400)
Document our meetings process
Document the goals of our meeting and written comms processes
=> Document our meetings process

README.md, development/README.md, hours-scheduling/README.md, social-rules/README.md
Hello @nicks,
Please review the following commits I made in branch nicks/wa:
323c0e7442c42ee5384aba4f097438cd4c007fc2 (2020-06-03 09:51:20 -0400)
port more working agreement things to the company repo
=> port more working agreement things to the company repo

README.md, expenses/README.md
I noticed that this is already covered in company-private.
=> Remove Expenses page

README.md
Much process has been written for which it is unclear what problem it is trying to solve. Without an understanding of a process's goal, it has difficult for others to:
1. review the process
2. follow the process
3. provide feedback on the process
4. improve the process to better meet its goals
Specify that we include problem descriptions in non-trivial PRs.
=> company: include problem statements in PRs

README.md, interviews/README.md, interviews/engineering.md
Hello @victorwuky, @dbentley, @maiamcc, @landism, @jazzdan, @hyu,
Please review the following commits I made in branch nicks/interviews:
d29e9f3f148977a11f8ed96382a5d7dd08bb959c (2020-07-15 10:20:57 -0400)
interviews: publish our interview formats to the company repo
=> interviews: publish our interview formats to the company repo

donations/README.md
Hello @nicks,
Please review the following commits I made in branch nicks/donations:
8f38762bd091d9fd59269b581e875fdefb72f552 (2020-07-29 12:42:01 -0400)
fill in donation schedule thru the end of the year
=> fill in donation schedule thru the end of the year

interviews/README.md, interviews/design.md, interviews/engineering.md
Hello @dbentley, @victorwuky, @hyu, @ellenkorbes,
Please review the following commits I made in branch nicks/productdesigner:
c8dd2d1f4694bef982b21b7213d67daf1643d2f7 (2020-08-04 21:06:25 -0400)
interviews: flesh out the eng rubric a bit, publish the design rubric
=> interviews: flesh out the eng rubric a bit, publish the design rubric

interviews/engineering.md
Hello @landism,
Please review the following commits I made in branch nicks/algorithmic:
196e0453e320225425034ab1eb799df2bf50c46c (2020-08-14 14:24:06 -0400)
remove the word 'algorithmic' from coding question
=> remove the word 'algorithmic' from coding question

interviews/README.md, interviews/feedback.md
Hello @dbentley, @maiamcc, @landism, @hyu,
Please review the following commits I made in branch nicks/interview-feedback:
5aa69284dd4337f67aa6738f8e540233badb0645 (2020-10-12 13:26:40 -0400)
interviews: add a sample feedback form
=> interviews: add a sample feedback form

donations/README.md
Hello @,
Please review the following commits I made in branch maiamcc/oct-donation:
e9053de6c2efb5083498e994702d7c454d04295d (2020-11-02 08:43:25 -0500)
add oct donation
=> add oct donation

retros/README.md
Hello @nicks,
Please review the following commits I made in branch maiamcc/dec-retro:
a78d0dc3d7b89146d18ceb094f2e3b7211fc2703 (2020-11-19 12:08:20 -0500)
retro: nick leads dec retro
=> retro: nick leads dec retro

product-principles/README.md
Hello @ellenkorbes, @victorwuky, @dbentley,
Please review the following commits I made in branch nicks/principles:
cf80493fd62cd330cc629a02262c64b23e84f74e (2020-12-14 13:59:31 -0500)
product-principles: extensibility
=> product-principles: extensibility

security/incident-response-plan.md
Please review the following commits I made in branch nicks/secrurity:
557564ccaefd214a35cda919dae60721087d8f3e (2020-12-18 13:13:22 -0500)
incident response plan
=> incident response plan

security/risk-assessment-program.md
Please review the following commits I made in branch nicks/risk:
c52b0be8a5f9af8a58f4e33c564b0d6f538b1614 (2020-12-18 13:23:39 -0500)
risk assessment policy
=> risk assessment policy

security/acceptable-use-policy.md, security/access-control-policy.md
Please review the following commits I made in branch nicks/access-control:
63a2b80ff6f83d8474774e75514d71517301049f (2020-12-18 13:42:15 -0500)
access controls and acceptable use
=> access controls and acceptable use

README.md, security/README.md
Please review the following commits I made in branch nicks/security:
14bc866251d7101a5543f31cd3642bae5cf22f6a (2020-12-18 14:30:52 -0500)
security: add Tilt security policies to company README
=> security: add Tilt security policies to company README

interviews/README.md, interviews/internships.md
Hello @maiamcc, @dbentley,
Please review the following commits I made in branch nicks/intern:
1427c537d31e237782813bb65fc0ff1723258073 (2021-01-19 17:54:22 -0500)
interviews: add a doc on the internship program
=> interviews: add a doc on the internship program

communications/README.md, product-development/README.md
Please review the following commits I made in branch nicks/updates:
b28fe000456a7582ac0734ffd07f1de3954308f7 (2021-02-19 18:32:44 -0500)
product-development: update notes on meetings
=> product-development: update notes on meetings

README.md
Hello @dbentley, @ellenkorbes, @hyu,
Please review the following commits I made in branch nicks/handbook:
bb25894d467112f47c57a68e5796f25fe47d6a1b (2021-03-15 15:22:47 -0400)
Add a handbook update policy
=> Add a handbook update policy

OWNERS, README.md, brand/OWNERS, communications/OWNERS, development/OWNERS, development/README.md, donations/OWNERS, hours-scheduling/OWNERS, interviews/OWNERS, interviews/README.md, personas/README.md, product-development/OWNERS, product-principles/OWNERS, retros/OWNERS, retros/README.md, security/OWNERS, social-rules/OWNERS, social-rules/README.md, user-support/OWNERS, user-support/README.md
Hello @nicks,
Please review the following commits I made in branch nicks/responsibilities:
8be7dd5283b5d803b2f8168eafb08d217bfd362e (2021-03-30 16:59:29 -0400)
assign myself as owner of all current docs
=> assign myself as owner of all current docs

brand/OWNERS, brand/README.md
Hello @surbhisgupta, @hyu,
Please review the following commits I made in branch nicks/brand:
1825b29c18cbf874f919b33899ef9af24492072a (2021-03-30 17:25:01 -0400)
brand: update the brand assets to point to the source of truth, and hand off the brand policy
=> brand: update the brand assets to point to the source of truth, and hand off the brand policy

security/OWNERS, security/incident-response-plan.md
Hello @ellenkorbes,
Please review the following commits I made in branch nicks/security:
9a2b09e5a6c7fdb77ba112dc03f771344de064b1 (2021-03-30 18:11:53 -0400)
security: with great titles come great responsibilities
=> security: with great titles come great responsibilities

donations/README.md
Hello @hyu,
Please review the following commits I made in branch nicks/donations:
a325a2552534111e60efa39f8dbc4e1f302d7e91 (2021-05-03 16:32:38 -0400)
donations: propose a donation schedule
=> donations: propose a donation schedule

product-development/OWNERS, product-development/README.md
Hello @ellenkorbes,
Please review the following commits I made in branch nicks/product-development:
05d86e60c9f5fc45d00112e95018aa83983f10a5 (2021-03-30 18:05:17 -0400)
product-development: clean up, update policies to reflect L as head of product
=> product-development: clean up, update policies to reflect L as head of product

interviews/README.md, interviews/advocate.md
Hello @ellenkorbes, @dbentley,
Please review the following commits I made in branch nicks/devrel:
e8d6ceff8dce8205fe288d8de4e1a96f4a8e0929 (2021-06-30 12:22:56 -0400)
interviews: publish our Dev Advocate interview guide
=> interviews: publish our Dev Advocate interview guide

interviews/README.md
Hello @nicks,
Please review the following commits I made in branch nicks/ceo:
773344f286bb91b4b6dc3ef0185f984cd8709c03 (2021-10-01 11:00:29 -0400)
update interview process
=> update interview process

donations/README.md
Hello @lizzthabet,
Please review the following commits I made in branch nicks/data:
631feec4480be70088a94e4a4d37676bdf6f245a (2021-11-29 15:37:40 -0500)
donations: add Nobember, July
=> donations: add Nobember, July
